[2022-07-16 12:53:54,195] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: car_price_prediction.pipeline manual__2022-07-16T12:53:48.801609+00:00 [queued]>
[2022-07-16 12:53:54,436] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: car_price_prediction.pipeline manual__2022-07-16T12:53:48.801609+00:00 [queued]>
[2022-07-16 12:53:54,439] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 12:53:54,460] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-16 12:53:54,526] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 12:53:54,608] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): pipeline> on 2022-07-16 12:53:48.801609+00:00
[2022-07-16 12:53:54,705] {standard_task_runner.py:52} INFO - Started process 3514 to run task
[2022-07-16 12:53:54,730] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'manual__2022-07-16T12:53:48.801609+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmp7zdqyyww', '--error-file', '/tmp/tmp6ao3td3s']
[2022-07-16 12:53:54,748] {standard_task_runner.py:80} INFO - Job 55: Subtask pipeline
[2022-07-16 12:53:55,188] {task_command.py:371} INFO - Running <TaskInstance: car_price_prediction.pipeline manual__2022-07-16T12:53:48.801609+00:00 [running]> on host 744d078d7eff
[2022-07-16 12:53:55,569] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=car_price_prediction
AIRFLOW_CTX_TASK_ID=pipeline
AIRFLOW_CTX_EXECUTION_DATE=2022-07-16T12:53:48.801609+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-16T12:53:48.801609+00:00
[2022-07-16 12:53:59,423] {pipeline.py:116} INFO - model: LogisticRegression, acc_mean: 0.7591, acc_std: 0.0075
[2022-07-16 12:54:43,053] {pipeline.py:116} INFO - model: RandomForestClassifier, acc_mean: 0.7763, acc_std: 0.0057
[2022-07-16 12:55:22,556] {pipeline.py:116} INFO - model: SVC, acc_mean: 0.7871, acc_std: 0.0042
[2022-07-16 12:55:22,559] {pipeline.py:121} INFO - best model: SVC, accuracy: 0.7871
[2022-07-16 12:55:36,908] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/modules/pipeline.py", line 126, in pipeline
    with open(model_filename, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/models/cars_pipe.pkl'
[2022-07-16 12:55:36,938] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=pipeline, execution_date=20220716T125348, start_date=20220716T125354, end_date=20220716T125536
[2022-07-16 12:55:36,995] {standard_task_runner.py:97} ERROR - Failed to execute job 55 for task pipeline ([Errno 2] No such file or directory: '/opt/airflow/data/models/cars_pipe.pkl'; 3514)
[2022-07-16 12:55:37,115] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-16 12:55:37,193] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
