[2022-07-16 12:41:55,539] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: car_price_prediction.pipeline manual__2022-07-16T12:41:49.115334+00:00 [queued]>
[2022-07-16 12:41:55,567] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: car_price_prediction.pipeline manual__2022-07-16T12:41:49.115334+00:00 [queued]>
[2022-07-16 12:41:55,569] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 12:41:55,570] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-16 12:41:55,571] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 12:41:55,632] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): pipeline> on 2022-07-16 12:41:49.115334+00:00
[2022-07-16 12:41:55,654] {standard_task_runner.py:52} INFO - Started process 3133 to run task
[2022-07-16 12:41:55,683] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'manual__2022-07-16T12:41:49.115334+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpg9sh39wb', '--error-file', '/tmp/tmpquc1ly18']
[2022-07-16 12:41:55,689] {standard_task_runner.py:80} INFO - Job 53: Subtask pipeline
[2022-07-16 12:41:55,928] {task_command.py:371} INFO - Running <TaskInstance: car_price_prediction.pipeline manual__2022-07-16T12:41:49.115334+00:00 [running]> on host 744d078d7eff
[2022-07-16 12:41:56,397] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=car_price_prediction
AIRFLOW_CTX_TASK_ID=pipeline
AIRFLOW_CTX_EXECUTION_DATE=2022-07-16T12:41:49.115334+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-16T12:41:49.115334+00:00
[2022-07-16 12:42:02,276] {pipeline.py:116} INFO - model: LogisticRegression, acc_mean: 0.7591, acc_std: 0.0075
[2022-07-16 12:43:04,277] {pipeline.py:116} INFO - model: RandomForestClassifier, acc_mean: 0.7763, acc_std: 0.0057
[2022-07-16 12:44:18,701] {pipeline.py:116} INFO - model: SVC, acc_mean: 0.7871, acc_std: 0.0042
[2022-07-16 12:44:18,708] {pipeline.py:121} INFO - best model: SVC, accuracy: 0.7871
[2022-07-16 12:44:45,197] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/modules/pipeline.py", line 126, in pipeline
    with open(model_filename, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/models/cars_pipe.pkl'
[2022-07-16 12:44:45,253] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=pipeline, execution_date=20220716T124149, start_date=20220716T124155, end_date=20220716T124445
[2022-07-16 12:44:45,290] {standard_task_runner.py:97} ERROR - Failed to execute job 53 for task pipeline ([Errno 2] No such file or directory: '/opt/airflow/data/models/cars_pipe.pkl'; 3133)
[2022-07-16 12:44:45,371] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-16 12:44:45,532] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
