[2022-07-16 12:41:51,615] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: car_price_prediction.pipeline manual__2022-07-16T12:38:24.115312+00:00 [queued]>
[2022-07-16 12:41:51,657] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: car_price_prediction.pipeline manual__2022-07-16T12:38:24.115312+00:00 [queued]>
[2022-07-16 12:41:51,659] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 12:41:51,661] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-07-16 12:41:51,662] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 12:41:51,693] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): pipeline> on 2022-07-16 12:38:24.115312+00:00
[2022-07-16 12:41:51,709] {standard_task_runner.py:52} INFO - Started process 3124 to run task
[2022-07-16 12:41:51,715] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'manual__2022-07-16T12:38:24.115312+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpf7vy0g0d', '--error-file', '/tmp/tmp85wen9is']
[2022-07-16 12:41:51,718] {standard_task_runner.py:80} INFO - Job 52: Subtask pipeline
[2022-07-16 12:41:51,933] {task_command.py:371} INFO - Running <TaskInstance: car_price_prediction.pipeline manual__2022-07-16T12:38:24.115312+00:00 [running]> on host 744d078d7eff
[2022-07-16 12:41:52,188] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=car_price_prediction
AIRFLOW_CTX_TASK_ID=pipeline
AIRFLOW_CTX_EXECUTION_DATE=2022-07-16T12:38:24.115312+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-16T12:38:24.115312+00:00
[2022-07-16 12:41:58,118] {pipeline.py:116} INFO - model: LogisticRegression, acc_mean: 0.7591, acc_std: 0.0075
[2022-07-16 12:43:01,839] {pipeline.py:116} INFO - model: RandomForestClassifier, acc_mean: 0.7763, acc_std: 0.0057
[2022-07-16 12:44:12,826] {pipeline.py:116} INFO - model: SVC, acc_mean: 0.7871, acc_std: 0.0042
[2022-07-16 12:44:12,829] {pipeline.py:121} INFO - best model: SVC, accuracy: 0.7871
[2022-07-16 12:44:37,030] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/modules/pipeline.py", line 126, in pipeline
    with open(model_filename, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/models/cars_pipe.pkl'
[2022-07-16 12:44:37,060] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=car_price_prediction, task_id=pipeline, execution_date=20220716T123824, start_date=20220716T124151, end_date=20220716T124437
[2022-07-16 12:44:37,205] {standard_task_runner.py:97} ERROR - Failed to execute job 52 for task pipeline ([Errno 2] No such file or directory: '/opt/airflow/data/models/cars_pipe.pkl'; 3124)
[2022-07-16 12:44:37,411] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-16 12:44:37,712] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
